
name: Build Native Termux Wheel

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    # This tells GitHub to run the job INSIDE the Termux emulator
    container:
      image: ghcr.io/termux/termux-docker:aarch64 
    
    steps:
      - name: Update Termux and Install Build Tools
        run: |
          pkg update -y
          pkg install -y python rust binutils clang make pkg-config

      - name: Build the Python Package
        run: |
          export CARGO_BUILD_TARGET=aarch64-linux-android
          pip wheel mitmproxy-rs==0.12.9
          
      - name: Upload Native Wheel
        uses: actions/upload-artifact@v4
        with:
          name: native-termux-wheel
          path: ./*.whl
